<?php

namespace App\Http\Controllers\Public;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Services\VotingService;
use App\Models\VotingSession;

class VotingController extends Controller
{
    protected VotingService $service;

    public function __construct(VotingService $service)
    {
        $this->service = $service;
    }

    /**
     * Display all active/upcoming voting sessions.
     */
    public function index()
    {
        $sessions = VotingSession::whereIn('status', ['active', 'upcoming'])
            ->withCount('candidates')
            ->withCount('votes')
            ->orderBy('start_date', 'asc')
            ->get();

        $pastSessions = VotingSession::where('status', 'closed')
            ->where('results_visibility', 'public')
            ->withCount('candidates')
            ->withCount('votes')
            ->orderBy('end_date', 'desc')
            ->take(3)
            ->get();

        return view('public.voting.index', compact('sessions', 'pastSessions'));
    }

    /**
     * Display the voting booth for a specific session.
     */
    public function show(Request $request, string $slug)
    {
        $session = VotingSession::where('slug', $slug)
            ->with(['candidates' => function ($q) {
                $q->withCount('votes')->orderBy('order');
            }])
            ->firstOrFail();

        // Check if authenticated user has already voted
        $hasVoted = false;
        $userVote = null;
        if ($request->user()) {
            $userVote = $session->votes()->where('user_id', $request->user()->id)->first();
            $hasVoted = (bool) $userVote;
        }

        // Resolve whether results should be shown
        $showResults = $session->status === 'closed' && $session->results_visibility === 'public';
        if ($hasVoted && $session->results_visibility !== 'hidden') {
            $showResults = true;
        }

        // Total votes for percentage calculation
        $totalVotes = $session->votes()->count();

        return view('public.voting.show', compact(
            'session',
            'hasVoted',
            'userVote',
            'showResults',
            'totalVotes'
        ));
    }

    /**
     * Cast a vote for a candidate.
     */
    public function store(Request $request, string $slug)
    {
        // 1. Verify Authentication & Email Verification
        if (!$request->user() || !$request->user()->hasVerifiedEmail()) {
            abort(403, 'You must be logged in and verified to vote.');
        }

        // 2. Validate input
        $request->validate([
            'candidate_id' => 'required|exists:candidates,id',
            'fingerprint' => 'nullable|string', // Should be generated by frontend JS
        ]);

        $session = VotingSession::where('slug', $slug)->firstOrFail();

        // 3. Fallback fingerprint if frontend didn't supply one (User Agent)
        $fingerprint = $request->input('fingerprint', $request->userAgent() ?? 'unknown');

        try {
            $this->service->castVote(
                $session->id,
                $request->input('candidate_id'),
                $request->user()->id,
                $request->ip(),
                $fingerprint
            );

            return redirect()->route('public.voting.show', $slug)->with('success', 'Your vote has been securely recorded.');
        } catch (\App\Exceptions\DoubleVoteException $e) {
            return redirect()->back()->with('error', $e->getMessage());
        } catch (\Exception $e) {
            return redirect()->back()->with('error', $e->getMessage());
        }
    }
}
