<?php

namespace App\Http\Controllers\Public;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Validation\Rule;
use App\Services\VotingService;
use App\Models\VotingSession;

class VotingController extends Controller
{
    protected VotingService $service;

    public function __construct(VotingService $service)
    {
        $this->service = $service;
    }

    /**
     * Display all active/upcoming voting sessions.
     */
    public function index()
    {
        $sessions = VotingSession::where('status', VotingSession::STATUS_ACTIVE)
            ->withCount('candidates')
            ->withCount('votes')
            ->orderBy('start_date', 'asc')
            ->get();

        $pastSessions = VotingSession::where('status', VotingSession::STATUS_COMPLETED)
            ->where('results_visibility', VotingSession::VISIBILITY_PUBLIC)
            ->withCount('candidates')
            ->withCount('votes')
            ->orderBy('end_date', 'desc')
            ->take(3)
            ->get();

        return view('public.voting.index', compact('sessions', 'pastSessions'));
    }

    /**
     * Display the voting booth for a specific session.
     */
    public function show(Request $request, string $slug)
    {
        $session = VotingSession::where('slug', $slug)
            ->publiclyVisible()
            ->with(['candidates' => function ($q) {
                $q->withCount('votes')->orderBy('order');
            }])
            ->firstOrFail();

        // Check if authenticated user has already voted
        $hasVoted = false;
        $userVote = null;
        if ($request->user()) {
            $userVote = $session->votes()->where('user_id', $request->user()->id)->first();
            $hasVoted = (bool) $userVote;
        }

        // Resolve whether results should be shown (see VotingSession::resultsVisibleTo)
        $showResults = $session->resultsVisibleTo($request->user(), $hasVoted);

        // Total votes for percentage calculation
        $totalVotes = $session->votes()->count();

        return view('public.voting.show', compact(
            'session',
            'hasVoted',
            'userVote',
            'showResults',
            'totalVotes'
        ));
    }

    /**
     * Cast a vote for a candidate.
     */
    public function store(Request $request, string $slug)
    {
        // 1. Verify Authentication & Email Verification
        if (!$request->user() || !$request->user()->hasVerifiedEmail()) {
            abort(403, 'You must be logged in and verified to vote.');
        }

        $session = VotingSession::where('slug', $slug)->publiclyVisible()->firstOrFail();

        // 2. Validate input. The candidate must belong to THIS session — a bare
        // exists:candidates,id would let a voter pick a candidate from another ballot.
        $request->validate([
            'candidate_id' => [
                'required',
                Rule::exists('candidates', 'id')->where(
                    fn ($query) => $query->where('voting_session_id', $session->id)
                                         ->whereNull('deleted_at')
                ),
            ],
            'fingerprint' => 'nullable|string|max:255', // Should be generated by frontend JS
        ]);

        // 3. Fallback fingerprint if frontend didn't supply one (User Agent).
        // The hidden input posts "" when JS is off, so use ?: rather than a
        // default argument, which only fires on a missing key.
        $fingerprint = $request->input('fingerprint') ?: ($request->userAgent() ?? 'unknown');

        try {
            $this->service->castVote(
                $session->id,
                $request->input('candidate_id'),
                $request->user()->id,
                $request->ip(),
                $fingerprint
            );

            return redirect()->route('public.voting.show', $slug)->with('success', 'Your vote has been securely recorded.');
        } catch (\App\Exceptions\DoubleVoteException $e) {
            return redirect()->back()->with('error', $e->getMessage());
        } catch (\Exception $e) {
            return redirect()->back()->with('error', $e->getMessage());
        }
    }
}
